#!/bin/bash


API_URL="https://pokeapi.co/api/v2/pokemon/pikachu"


DATA_FILE="data.json"
ERROR_FILE="errors.txt"


curl -s -o "$DATA_FILE" -w "%{http_code}" "$API_URL" > status_code.txt


STATUS_CODE=$(cat status_code.txt)
rm status_code.txt


if [ "$STATUS_CODE" -ne 200 ]; then
    echo "Error: Failed to retrieve data for Pikachu. Status code: $STATUS_CODE" >> "$ERROR_FILE"
    exit 1
else
    echo "Data saved successfully to $DATA_FILE"
fi

