#!/bin/bash



data_file="data.json"


name=$(jq -r '.name' "$data_file")
height=$(jq -r '.height' "$data_file")
weight=$(jq -r '.weight' "$data_file")
type=$(jq -r '.types[0].type.name' "$data_file")


formatted_height=$(echo "$height" | awk '{printf "%.1f", $1 / 10}')
formatted_weight=$(echo "$weight" | awk '{printf "%.0f", $1 / 10}')


type=$(echo "$type" | sed 's/.*/\u&/')


echo "$name is of type $type, weighs ${formatted_weight}kg, and is ${formatted_height}m tall."


